[package]
name = "noise-storage-memory"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "In-memory storage backend for Noise search engine"
edition = "2021"

[dependencies]
noise-storage = { path = "../noise-storage" }
self_cell = "1.0"

[dev-dependencies]
noise-tests = { path = "../noise-tests" }
noise_search = { path = ".." }
