[package]
name = "noise-storage-memory"
version = "0.1.0"
authors = { workspace = true }
description = "In-memory storage backend for Noise search engine"
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
noise-storage = { workspace = true }
self_cell = { workspace = true }

[dev-dependencies]
noise-tests = { workspace = true }
noise_search = { workspace = true }
