extern crate capnp;
extern crate rocksdb;

mod error;
mod filters;
mod json_shred;
mod key_builder;
mod stems;
pub mod index;
pub mod query;

// include capnp code generated by `build.rs`
mod records_capnp {
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/records_capnp.rs"));
}
