extern crate capnp;

mod json_shred;
mod key_builder;
mod stems;
pub mod index;

// include capnp code generated by `build.rs`
mod records_capnp {
    #![allow(dead_code)]
    include!(concat!(env!("OUT_DIR"), "/records_capnp.rs"));
}
